tages:
  - build
  - test
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  script:
    - docker build -t flask-app-1:latest .
  tags:
    - dev


test_job:
  stage: test
  script:
    - echo "testing....."
  tags:
    - dev

push_job:
  stage: push_to_dockerhub
  script:
    - docker login -u $DockerUser -p $DockerPass
    - docker image tag flask-app-1:latest  $DockerUser/notes-app-1:latest
    - docker push $DockerUser/flask-app-1:latest
  tags:
    - dev




deploy_job:
  stage: deploy
  script:
    - docker compose up -d
  tags:
    - dev

