version: '3.9'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: todo_db
    networks:
      - two-tier
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier
volumes:
  mysql-data:
networks:
  two-tier:
    driver: bridge
