apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
  - name: two-tier-app-pod
    image: nikhilpal1994/flask-app-1:latest
    env:
      - name: MYSQL_HOST
        value: "10.106.126.215"          # this is your mysql's service clusture IP, Make sure to change it with yours
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_DB
        value: "todo_app"
    ports:
      - containerPort: 5000
    imagePullPolicy: Always
