apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: two-tier-ns
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image:  nikhilpal1994/mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
    volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
            
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: two-tier-ns
data:
  init.sql: |
    CREATE DATABASE todo_app;
    USE todo_app;

    CREATE TABLE tasks (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      status BOOLEAN DEFAULT FALSE
);
